project:
  type: website
  output-dir: _site

format:
  html:
    toc: true
    # theme: cosmo

website:
  title: "Environments"
  google-analytics: "UA-20375833-3"
  site-url: https://environments.rstudio.com
  repo-url: https://github.com/rstudio/environments.rstudio.com
  repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    right:
      - text: "Use cases"
        file: docs/upgrades.qmd
      - text: "Strategies"
        file: docs/reproduce.qmd
      - text: "Tools"
        file: docs/comparison-of-tools.qmd

  sidebar:

    - id: use-cases
      title: "Use Cases"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Safely Upgrade Packages"
          file: docs/upgrades.qmd
        - text: "Validate your Environment"
          file: docs/validation.qmd
        - text: "Deploy to Production"
          file: docs/deploy.qmd
        - text: "Collaborate within a Team"
          file: docs/collaborate.qmd

    - id: strategies
      title: "Strategies"
      collapse-level: 1
      style: "docked"
      contents:
        - text: "Strategy Map"
          file: docs/reproduce.qmd
        - text: "Snapshot and Restore"
          file: docs/snapshot.qmd
        - text: "Shared Baseline"
          file: docs/shared.qmd
        - text: "Validated"
          file: docs/validated.qmd

    - id: tools
      title: "Tools"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Comparison of tools"
          file: docs/comparison-of-tools.qmd

        - section: "R"
          contents:
            - text: "Introduction"
              file: docs/r/introduction.qmd
            - text: "renv"
              file: docs/r/renv.qmd

        - section: "Python"
          contents:
            - text: "Introduction"
              file: docs/python/introduction.qmd
            - text: "venv"
              file: docs/python/venv.qmd
            - text: "Poetry"
              file: docs/python/poetry.qmd
            - text: "Conda"
              file: docs/python/conda.qmd

        - section: "Old stuff"
          contents:
            - text: "Installing - pak / remotes"
              file: docs/installation.qmd
            - text: "Repositories - RStudio Package Manager"
              file: docs/repositories.qmd
            - text: "Libraries - renv"
              file: docs/libraries.qmd
            - text: "R Versions"
              file: docs/R-installation.qmd
            - text: "Docker"
              file: docs/Docker.qmd
            - text: "Python"
              file: docs/python.qmd
