project:
  type: website
  output-dir: _site

format:
  html:
    toc: true
    # theme: cosmo

website:
  title: "Environments"
  google-analytics: "UA-20375833-3"
  site-url: https://environments.rstudio.com
  repo-url: https://github.com/rstudio/environments.rstudio.com
  repo-actions: [edit, issue]
  page-navigation: true

  navbar:
    right:
      - text: "Use cases"
        href: docs/upgrades.qmd
      - text: "Strategies"
        href: docs/reproduce.qmd
      - text: "Tools"
        href: docs/comparison-of-tools.qmd

  sidebar:

    - id: use-cases
      title: "Use Cases"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Safely Upgrade Packages"
          href: docs/upgrades.qmd
        - text: "Validate your Environment"
          href: docs/validation.qmd
        - text: "Deploy to Production"
          href: docs/deploy.qmd
        - text: "Collaborate within a Team"
          href: docs/collaborate.qmd
    
    - id: strategies
      title: "Strategies"
      collapse-level: 1
      style: "docked"
      contents:
        - text: "Strategy Map"
          href: docs/reproduce.qmd
        - text: "Snapshot and Restore"
          href: docs/snapshot.qmd
        - text: "Shared Baseline"
          href: docs/shared.qmd
        - text: "Validated"
          href: docs/validated.qmd
    
    - id: tools
      title: "Tools"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Comparison of tools"
          href: docs/comparison-of-tools.qmd

        - section: "R"
          contents:
            - text: "Introduction"
              href: docs/r/introduction.qmd
            - text: "renv"
              href: docs/r/renv.qmd

        - section: "Python"
          contents:
            - text: "Introduction"
              href: docs/python/introduction.qmd
            - text: "venv"
              href: docs/python/venv.qmd
            - text: "poetry"
              href: docs/python/poetry.qmd
            - text: "conda"
              href: docs/python/conda.qmd
        
        - section: "Old stuff"
          contents:
            - text: "Installing - pak / remotes"
              href: docs/installation.qmd
            - text: "Repositories - RStudio Package Manager"
              href: docs/repositories.qmd
            - text: "Libraries - renv"
              href: docs/libraries.qmd
            - text: "R Versions"
              href: docs/R-installation.qmd
            - text: "Docker"
              href: docs/Docker.qmd
            - text: "Python"
              href: docs/python.qmd
